steps:
  # Step 1: Daisy chain call to Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'trigger-cloud-deploy'
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-$SHORT_SHA'                                                       
      - '--delivery-pipeline=$_PIPELINE_NAME'             
      - '--region=$_REGION'                    
      - '--source=.'                      

options:
  logging: CLOUD_LOGGING_ONLY