steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    id: 'infra-manager-preview-prod'
    env:
      - 'SHORT_SHA=${SHORT_SHA}'
    script: |
      #!/bin/sh
      set -e
      
      echo "🔍 Creating dry-run Infrastructure Manager Preview for PROD using local-source..."
      # Truncate Preview ID to be safely below 40 characters:
      PREV_ID=$(echo "p-pr-${SHORT_SHA}-prod" | cut -c 1-39)
      
      gcloud infra-manager previews create ${PREV_ID} \
        --local-source="./terraform" \
        --project="app1-prod-8c0e2f7a" \
        --location="us-east1" \
        --service-account="projects/app1-prod-8c0e2f7a/serviceAccounts/prod-pipeline-sa@app1-prod-8c0e2f7a.iam.gserviceaccount.com" \
        --input-values=project_id="app1-prod-8c0e2f7a",environment="prod" \
        --impersonate-service-account="prod-pipeline-sa@app1-prod-8c0e2f7a.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY