/*
 * Tesla Energy Service Engineering Data Engineer Evaluation
 *
 * API developed for take-home-assignment
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//

	"github.com/sarabrajsingh/restful-openapi/config"
	"github.com/sarabrajsingh/restful-openapi/internal/global_errors"
	"github.com/sarabrajsingh/restful-openapi/internal/logging"
	sw "github.com/sarabrajsingh/restful-openapi/internal/server"
	"github.com/sarabrajsingh/restful-openapi/internal/utils"
)

func main() {
	logger := logging.NewRealLogger()
	// in memory error store
	errorStore := global_errors.NewErrorStore()
	bodyReader := utils.DefaultBodyReader
	logger.Printf("Server started")

	config, err := config.NewConfig()
	if err != nil {
		log.Fatalf("Couldn't load config: %v", err)
	}

	server := sw.NewServer(config, logger, errorStore, bodyReader)
	router := server.NewRouter()
	port := ":8080"

	logger.Printf("API server is running on port %s\n", port)
	log.Fatal(http.ListenAndServe(port, router))
}
